export const BASE_URL = process.env.NODE_ENV === "development" ? "http://localhost:8000" : "";
// export const BASE_URL = "https://swift-cart.onrender.com";
// export const BASE_URL = "http://localhost4000";
// export const BASE = "https://swift-cart.onrender.com";
export const PRODUCTS_URL = "/api/products";
export const PRODUCTS_URL_ID = "/api/products/:id";
export const USERS_URL = "/api/users";
export const ORDERS_URL = "/api/orders";
export const PAYPAL_URL = "/api/config/paypal";
export const UPLOAD_URL = "/api/upload";
